<?php 
$_aClassFiles = array( 
	"AmazonAutoLinks_AutoLoad"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/AmazonAutoLinks_AutoLoad.php",
	"AmazonAutoLinks_Bootstrap"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/AmazonAutoLinks_Bootstrap.php",
	"AmazonAutoLinks_Properties"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/AmazonAutoLinks_Properties.php",
	"AmazonAutoLinks_RegisterClasses"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_RegisterClasses.php",
	"AmazonAutoLinks_DOM"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_DOM.php",
	"AmazonAutoLinks_Debug"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_Debug.php",
	"AmazonAutoLinks_Encrypt"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_Encrypt.php",
	"AmazonAutoLinks_HTMLElementReplacer"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_HTMLElementReplacer.php",
	"AmazonAutoLinks_ImageHandler"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_ImageHandler.php",
	"AmazonAutoLinks_ImportV1Options"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_ImportV1Options.php",
	"AmazonAutoLinks_ImportV2Options"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_ImportV2Options.php",
	"AmazonAutoLinks_Redirects"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_Redirects.php", 
	"AmazonAutoLinks_Requirements"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_Requirements.php", 
	"AmazonAutoLinks_SimplePie"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_SimplePie.php", 
	"AmazonAutoLinks_Utilities"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_Utilities.php", 
	"AmazonAutoLinks_WPUtilities"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_WPUtilities.php", 
	"AmazonAutoLinks_WPUtilities_Transient"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_WPUtilities_Transient.php", 
	"AmazonAutoLinks_SimplePie___"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_SimplePie.php", 
	"AmazonAutoLinks_SimplePie__"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_SimplePie.php", 
	"AmazonAutoLinks_SimplePie_Cache"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_SimplePie.php", 
	"AmazonAutoLinks_SimplePie_Cache_Transient"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_SimplePie.php", 
	"AmazonAutoLinks_SimplePie_File"	=>	AmazonAutoLinks_Commons::$sDirPath . "/include/class/boot/utility/AmazonAutoLinks_SimplePie.php", 
);