blank_issues_enabled: true
contact_links:
    - name: Technical support
      url: https://wordpress.org/support/plugin/amazon-auto-links/
      about: For technical support, create a new topic in the plugin support forum.