name: Feature request
description: Suggest an idea for this project
labels: ["suggestion"]
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this feature request! Please make sure there is no similar topic already posted.
    - type: textarea
      attributes:
          label: Description
          description: Is your feature request related to a problem? Please provide a clear and concise description of what the problem is.
          placeholder: |
              "I'm always frustrated when [...]" or "Currently, it is difficult to do [...]"
      validations:
          required: true

    - type: textarea
      attributes:
          label: Solution
          description: Describe the solution you'd like to see being implemented.
          placeholder: |
              "I'd like to see [...] being implmented."
      validations:
          required: true

    - type: textarea
      attributes:
          label: Images
          description: |
              A picture or screen recording clip which helps understand what you describe. To create a GIF screen recording, you can use LIEcap: https://www.cockos.com/licecap/
              Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
              Sharing a code snippet that demonstrates the issue also helps. For short snippets, post them here, or use Gist for long ones or mulitple files: https://gist.github.com
              Please ensure that your code can be run by others to reproduce and debug the issue.
      validations:
          required: false

    - type: dropdown
      id: existing
      attributes:
          label: Please confirm that you have searched existing issues in this repository.
          description: https://github.com/michaeluno/amazon-auto-links/issues
          multiple: true
          options:
             - 'Yes'
             - 'No'
      validations:
          required: true